-- Initial schema for Edd's Wallet, generated by `drizzle-kit generate`
-- from src/db/schema.ts and then hand-patched (this file, not the
-- generator) to add:
--   1. `STRICT` on every table (drizzle-kit's SQLite generator doesn't
--      emit it) - see data/edw-tech-research/report.md Section 3.
--   2. BEFORE UPDATE/DELETE triggers on cash_entries and credit_entries
--      that make the ledger append-only at the database engine level
--      (the block at the bottom of this file).
-- Any future `drizzle-kit generate` run for schema changes will need the
-- same two patches re-applied to its output by hand; drizzle-kit's diff
-- engine does not model STRICT or triggers.
--
-- WAL mode and `PRAGMA foreign_keys = ON` are connection-level settings,
-- not migration DDL - see src/db/connection.ts.

CREATE TABLE `accounts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`child_user_id` integer NOT NULL,
	`currency_label` text DEFAULT 'USD' NOT NULL,
	`created_at` text NOT NULL,
	FOREIGN KEY (`child_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
) STRICT;
--> statement-breakpoint
CREATE UNIQUE INDEX `accounts_child_user_id_unique` ON `accounts` (`child_user_id`);--> statement-breakpoint
CREATE TABLE `allowance_rules` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`account_id` integer NOT NULL,
	`pocket_id` integer NOT NULL,
	`amount_cents` integer NOT NULL,
	`frequency` text NOT NULL,
	`anchor_date` text NOT NULL,
	`memo` text,
	`active` integer DEFAULT 1 NOT NULL,
	`created_by_user_id` integer NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`pocket_id`) REFERENCES `pockets`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "allowance_rules_amount_positive" CHECK("allowance_rules"."amount_cents" > 0),
	CONSTRAINT "allowance_rules_frequency_check" CHECK("allowance_rules"."frequency" in ('weekly', 'biweekly', 'monthly'))
) STRICT;
--> statement-breakpoint
CREATE INDEX `allowance_rules_account_id_idx` ON `allowance_rules` (`account_id`);--> statement-breakpoint
CREATE TABLE `audit_log` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`actor_user_id` integer NOT NULL,
	`action` text NOT NULL,
	`entity_type` text NOT NULL,
	`entity_id` integer NOT NULL,
	`detail_json` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`actor_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
) STRICT;
--> statement-breakpoint
CREATE TABLE `cash_entries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`pocket_id` integer NOT NULL,
	`amount_cents` integer NOT NULL,
	`entry_type` text NOT NULL,
	`transfer_group_id` text,
	`source_type` text,
	`source_id` integer,
	`memo` text,
	`created_by_user_id` integer NOT NULL,
	`balance_after_cents` integer NOT NULL,
	`created_at` text NOT NULL,
	FOREIGN KEY (`pocket_id`) REFERENCES `pockets`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "cash_entries_amount_nonzero" CHECK("cash_entries"."amount_cents" != 0),
	CONSTRAINT "cash_entries_entry_type_check" CHECK("cash_entries"."entry_type" in ('deposit', 'withdrawal', 'allowance_payout', 'transfer_in', 'transfer_out', 'loan_disbursement', 'loan_repayment', 'credit_card_payment', 'interest_earned', 'adjustment')),
	CONSTRAINT "cash_entries_source_type_check" CHECK("cash_entries"."source_type" is null or "cash_entries"."source_type" in ('allowance_rule', 'credit_line', 'manual'))
) STRICT;
--> statement-breakpoint
CREATE INDEX `cash_entries_pocket_id_idx` ON `cash_entries` (`pocket_id`,`id`);--> statement-breakpoint
CREATE TABLE `concept_unlocks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`account_id` integer NOT NULL,
	`concept_key` text NOT NULL,
	`unlocked_at` text,
	`unlocked_by_user_id` integer,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`unlocked_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "concept_unlocks_concept_key_check" CHECK("concept_unlocks"."concept_key" in ('balance', 'allowance', 'savings_interest', 'loans', 'credit_card'))
) STRICT;
--> statement-breakpoint
CREATE UNIQUE INDEX `concept_unlocks_account_id_concept_key_unique` ON `concept_unlocks` (`account_id`,`concept_key`);--> statement-breakpoint
CREATE TABLE `credit_entries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`credit_line_id` integer NOT NULL,
	`amount_cents` integer NOT NULL,
	`entry_type` text NOT NULL,
	`linked_cash_entry_id` integer,
	`memo` text,
	`created_by_user_id` integer NOT NULL,
	`owed_after_cents` integer NOT NULL,
	`created_at` text NOT NULL,
	FOREIGN KEY (`credit_line_id`) REFERENCES `credit_lines`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`linked_cash_entry_id`) REFERENCES `cash_entries`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "credit_entries_amount_nonzero" CHECK("credit_entries"."amount_cents" != 0),
	CONSTRAINT "credit_entries_entry_type_check" CHECK("credit_entries"."entry_type" in ('disbursement', 'purchase', 'interest_charge', 'payment', 'forgiveness'))
) STRICT;
--> statement-breakpoint
CREATE INDEX `credit_entries_credit_line_id_idx` ON `credit_entries` (`credit_line_id`,`id`);--> statement-breakpoint
CREATE TABLE `credit_lines` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`account_id` integer NOT NULL,
	`kind` text NOT NULL,
	`label` text NOT NULL,
	`principal_or_limit_cents` integer NOT NULL,
	`apr_bps` integer DEFAULT 0 NOT NULL,
	`installment_amount_cents` integer,
	`installment_frequency` text,
	`statement_day` integer,
	`status` text DEFAULT 'active' NOT NULL,
	`opened_at` text NOT NULL,
	`closed_at` text,
	`created_by_user_id` integer NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "credit_lines_kind_check" CHECK("credit_lines"."kind" in ('installment_loan', 'credit_card')),
	CONSTRAINT "credit_lines_installment_frequency_check" CHECK("credit_lines"."installment_frequency" is null or "credit_lines"."installment_frequency" in ('weekly', 'biweekly', 'monthly')),
	CONSTRAINT "credit_lines_status_check" CHECK("credit_lines"."status" in ('active', 'paid_off', 'frozen', 'forgiven'))
) STRICT;
--> statement-breakpoint
CREATE TABLE `pockets` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`account_id` integer NOT NULL,
	`kind` text NOT NULL,
	`name` text NOT NULL,
	`interest_rate_bps` integer DEFAULT 0 NOT NULL,
	`goal_cents` integer,
	`is_default` integer DEFAULT 0 NOT NULL,
	`archived_at` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "pockets_kind_check" CHECK("pockets"."kind" in ('spending', 'savings'))
) STRICT;
--> statement-breakpoint
CREATE UNIQUE INDEX `pockets_account_id_name_unique` ON `pockets` (`account_id`,`name`);--> statement-breakpoint
CREATE TABLE `sessions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` integer NOT NULL,
	`token_hash` text NOT NULL,
	`created_at` text NOT NULL,
	`expires_at` text NOT NULL,
	`revoked_at` text,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
) STRICT;
--> statement-breakpoint
CREATE UNIQUE INDEX `sessions_token_hash_unique` ON `sessions` (`token_hash`);--> statement-breakpoint
CREATE TABLE `users` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`role` text NOT NULL,
	`display_name` text NOT NULL,
	`pin_hash` text,
	`pin_salt` text,
	`birth_year` integer,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
	`archived_at` text,
	CONSTRAINT "users_role_check" CHECK("users"."role" in ('parent', 'child', 'system'))
) STRICT;
--> statement-breakpoint
-- Append-only ledger enforcement (report Section 2/3): a bug that tried to
-- mutate or delete a historical ledger row is rejected by SQLite itself,
-- independent of any application-level check.
CREATE TRIGGER cash_entries_no_update BEFORE UPDATE ON cash_entries
BEGIN
  SELECT RAISE(ABORT, 'ledger is append-only');
END;
--> statement-breakpoint
CREATE TRIGGER cash_entries_no_delete BEFORE DELETE ON cash_entries
BEGIN
  SELECT RAISE(ABORT, 'ledger is append-only');
END;
--> statement-breakpoint
CREATE TRIGGER credit_entries_no_update BEFORE UPDATE ON credit_entries
BEGIN
  SELECT RAISE(ABORT, 'ledger is append-only');
END;
--> statement-breakpoint
CREATE TRIGGER credit_entries_no_delete BEFORE DELETE ON credit_entries
BEGIN
  SELECT RAISE(ABORT, 'ledger is append-only');
END;
